# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_produto_evento.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_produto(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(327, 160)
        Dialog.setAutoFillBackground(False)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_buscar_produtos_evento = QtWidgets.QLineEdit(Dialog)
        self.line_buscar_produtos_evento.setGeometry(QtCore.QRect(20, 80, 231, 22))
        self.line_buscar_produtos_evento.setObjectName("line_buscar_produtos_evento")
        self.buscar_produto_evento = QtWidgets.QLabel(Dialog)
        self.buscar_produto_evento.setGeometry(QtCore.QRect(20, 10, 201, 31))
        self.buscar_produto_evento.setStyleSheet("font: 10pt \"Arial Black\";\n"
"color: black;\n"
"")
        self.buscar_produto_evento.setObjectName("buscar_produto_evento")
        self.evento_produto_label = QtWidgets.QLabel(Dialog)
        self.evento_produto_label.setGeometry(QtCore.QRect(20, 50, 211, 16))
        self.evento_produto_label.setObjectName("evento_produto_label")
        self.finalizar_produto_evento = QtWidgets.QPushButton(Dialog)
        self.finalizar_produto_evento.setGeometry(QtCore.QRect(220, 120, 81, 23))
        self.finalizar_produto_evento.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.finalizar_produto_evento.setStyleSheet("QPushButton {\n"
"    background-color: rgb(253, 188, 55);\n"
"    color: black;\n"
"    border-radius: 5px;\n"
"    font: 10pt \"Montserrat\";\n"
"    outline: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(244, 163, 0);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 2px solid  rgb(226, 151, 0);  /* Cor verde quando estiver em foco */\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.finalizar_produto_evento.setObjectName("finalizar_produto_evento")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.buscar_produto_evento.setText(_translate("Dialog", "PRODUTOS EM EVENTO"))
        self.evento_produto_label.setText(_translate("Dialog", "Digite o produto vinculado a este evento:"))
        self.finalizar_produto_evento.setText(_translate("Dialog", "OK"))
