# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DIALOG.UI'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1151, 557)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Finalizar = QtWidgets.QPushButton(Dialog)
        self.Finalizar.setGeometry(QtCore.QRect(980, 496, 151, 31))
        self.Finalizar.setStyleSheet("QPushButton {\n"
"    background-color: rgb(253, 188, 55);\n"
"    color: black;\n"
"    border-radius: 5px;\n"
"    font: 10pt \"Montserrat\";\n"
"    outline: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(244, 163, 0);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 2px solid  rgb(226, 151, 0);  /* Cor verde quando estiver em foco */\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.Finalizar.setObjectName("Finalizar")
        self.Renovar_label = QtWidgets.QLabel(Dialog)
        self.Renovar_label.setGeometry(QtCore.QRect(20, 26, 481, 31))
        self.Renovar_label.setStyleSheet("font: 16pt \"Arial Black\";\n"
"color: black;\n"
"")
        self.Renovar_label.setObjectName("Renovar_label")
        self.Adicionar = QtWidgets.QPushButton(Dialog)
        self.Adicionar.setGeometry(QtCore.QRect(1060, 86, 75, 41))
        self.Adicionar.setObjectName("Adicionar")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(20, 90, 940, 441))
        self.scrollArea.setStyleSheet("QScrollArea{\n"
"\n"
"background-color:white;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"                background-color: #f1f1f1;\n"
"                width: 8px;\n"
"                margin: 0px 0px 0px 0px;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
"                background-color: #FFD700;\n"
"                min-height: 20px;\n"
"                border-radius: 4px;\n"
"            }\n"
"            QScrollBar::add-line:vertical,\n"
"            QScrollBar::sub-line:vertical {\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:vertical,\n"
"            QScrollBar::sub-page:vertical {\n"
"                background: none;\n"
"            }\n"
"            QScrollBar:horizontal {\n"
"                background-color: #f1f1f1;\n"
"                height: 8px;\n"
"                margin: 0px 0px 0px 0px;\n"
"            }\n"
"            QScrollBar::handle:horizontal {\n"
"                background-color: #FFD700;\n"
"                min-width: 20px;\n"
"                border-radius: 4px;\n"
"            }\n"
"            QScrollBar::add-line:horizontal,\n"
"            QScrollBar::sub-line:horizontal {\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:horizontal,\n"
"            QScrollBar::sub-page:horizontal {\n"
"                background: none;\n"
"            }")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 938, 439))
        self.scrollAreaWidgetContents.setStyleSheet("background-color:white;\n"
"")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Produtos de Evento"))
        self.Finalizar.setText(_translate("Dialog", "Finalizar"))
        self.Renovar_label.setText(_translate("Dialog", "PRODUTOS DE EVENTO"))
        self.Adicionar.setText(_translate("Dialog", "Adicionar"))
