# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'renovar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(322, 181)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Renovar_label = QtWidgets.QLabel(Dialog)
        self.Renovar_label.setGeometry(QtCore.QRect(20, 10, 201, 31))
        self.Renovar_label.setStyleSheet("font: 10pt \"Arial Black\";\n"
"color: black;\n"
"")
        self.Renovar_label.setObjectName("Renovar_label")
        self.renovar_checkbox = QtWidgets.QCheckBox(Dialog)
        self.renovar_checkbox.setGeometry(QtCore.QRect(20, 120, 191, 17))
        self.renovar_checkbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.renovar_checkbox.setObjectName("renovar_checkbox")
        self.finalizar_renovar = QtWidgets.QPushButton(Dialog)
        self.finalizar_renovar.setGeometry(QtCore.QRect(220, 140, 81, 23))
        self.finalizar_renovar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.finalizar_renovar.setStyleSheet("QPushButton {\n"
"    background-color: rgb(253, 188, 55);\n"
"    color: black;\n"
"    border-radius: 5px;\n"
"    font: 10pt \"Montserrat\";\n"
"    outline: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(244, 163, 0);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 2px solid  rgb(226, 151, 0);  /* Cor verde quando estiver em foco */\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.finalizar_renovar.setObjectName("finalizar_renovar")
        self.line_renovar_quantidade = QtWidgets.QLineEdit(Dialog)
        self.line_renovar_quantidade.setGeometry(QtCore.QRect(20, 80, 191, 21))
        self.line_renovar_quantidade.setObjectName("line_renovar_quantidade")
        self.renovar_label_2 = QtWidgets.QLabel(Dialog)
        self.renovar_label_2.setGeometry(QtCore.QRect(20, 50, 211, 16))
        self.renovar_label_2.setObjectName("renovar_label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Renovar_label.setText(_translate("Dialog", "RENOVAR ESTOQUE"))
        self.renovar_checkbox.setText(_translate("Dialog", "Renovar com mesma quantidade"))
        self.finalizar_renovar.setText(_translate("Dialog", "OK"))
        self.renovar_label_2.setText(_translate("Dialog", "Digite a quantidade que deseja renovar:"))
