# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filterbotao.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(322, 218)
        Dialog.setAutoFillBackground(False)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.FiltroProdutos = QtWidgets.QLabel(Dialog)
        self.FiltroProdutos.setGeometry(QtCore.QRect(20, 10, 201, 31))
        self.FiltroProdutos.setStyleSheet("font: 10pt \"Arial Black\";\n"
"color: black;\n"
"")
        self.FiltroProdutos.setObjectName("FiltroProdutos")
        self.checkbox_esgotado = QtWidgets.QCheckBox(Dialog)
        self.checkbox_esgotado.setGeometry(QtCore.QRect(30, 50, 191, 17))
        self.checkbox_esgotado.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkbox_esgotado.setObjectName("checkbox_esgotado")
        self.checkbox_ativos = QtWidgets.QCheckBox(Dialog)
        self.checkbox_ativos.setGeometry(QtCore.QRect(30, 110, 171, 17))
        self.checkbox_ativos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkbox_ativos.setObjectName("checkbox_ativos")
        self.checkbox_pausados = QtWidgets.QCheckBox(Dialog)
        self.checkbox_pausados.setGeometry(QtCore.QRect(30, 80, 161, 17))
        self.checkbox_pausados.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkbox_pausados.setObjectName("checkbox_pausados")
        self.filter_aplicar_btn = QtWidgets.QPushButton(Dialog)
        self.filter_aplicar_btn.setGeometry(QtCore.QRect(180, 180, 131, 23))
        self.filter_aplicar_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.filter_aplicar_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(253, 188, 55);\n"
"    color: black;\n"
"    border-radius: 5px;\n"
"    font: 10pt \"Montserrat\";\n"
"    outline: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(244, 163, 0);\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 2px solid  rgb(226, 151, 0);  /* Cor verde quando estiver em foco */\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.filter_aplicar_btn.setObjectName("filter_aplicar_btn")
        self.checkbox_eventos = QtWidgets.QCheckBox(Dialog)
        self.checkbox_eventos.setGeometry(QtCore.QRect(30, 140, 171, 17))
        self.checkbox_eventos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkbox_eventos.setObjectName("checkbox_eventos")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.FiltroProdutos.setText(_translate("Dialog", "FILTROS PERSONALIZADOS"))
        self.checkbox_esgotado.setText(_translate("Dialog", "   Produtos Esgotados"))
        self.checkbox_ativos.setText(_translate("Dialog", "   Produtos Ativos"))
        self.checkbox_pausados.setText(_translate("Dialog", "   Produtos Pausados"))
        self.filter_aplicar_btn.setText(_translate("Dialog", "Aplicar"))
        self.checkbox_eventos.setText(_translate("Dialog", "   Produtos de Evento"))
