# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/ui/FrmLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, MainWindow):

        self.MainWindow = MainWindow  # Armazena referência ao MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1005, 600)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)  # Remove moldura
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)  # Torna a janela translúcida
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(90, 20, 461, 551))
        self.frame.setStyleSheet("    background-color: rgb(253, 188, 55);\n"
"border-radius: 10px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 250, 441, 301))
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Imagens/estoque2.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(32)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white;\n"
"font: 32pt \"Montserrat\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 150, 401, 111))
        self.label_3.setStyleSheet("color: white;\n"
"font: 12pt \"Montserrat\";\n"
"")
        self.label_3.setObjectName("label_3")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(539, 49, 361, 491))
        self.frame_2.setStyleSheet("background-color: white;\n"
"border-radius: 10px;\n"
"border: 4px solid  rgb(253, 188, 55);\n"
"\n"
"\n"
"color: white;\n"
"font: 10pt \"Montserrat\";\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(50, 80, 261, 41))
        self.label_4.setStyleSheet("color: gray;\n"
"font: 20pt \"Montserrat\";\n"
"border: 0px;")
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(50, 180, 271, 51))
        self.lineEdit.setStyleSheet("background-color: rgba(0, 0 , 0, 0);\n"
"border: 2px solid  rgb(253, 188, 55);\n"
"padding-left:10px;\n"
"color: black;\n"
"font: 10pt \"Montserrat\";")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 260, 271, 51))
        self.lineEdit_2.setStyleSheet("background-color: rgba(0, 0 , 0, 0);\n"
"border: 2px solid  rgb(253, 188, 55);\n"
"padding-left:10px;\n"
"color: black;\n"
"font: 10pt \"Montserrat\";")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(50, 380, 271, 51))
        self.pushButton.setStyleSheet("QPushButton {\n"
"border: 2px;\n"
"background-color: rgb(253, 188, 55);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(240, 174, 6);\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.btn_close = QtWidgets.QPushButton(self.frame_2)
        self.btn_close.setGeometry(QtCore.QRect(314, 20, 31, 31))
        self.btn_close.setStyleSheet("QPushButton{\n"
"background-color: rgb(225, 0, 0);\n"
"border-color: rgb(225, 0, 0);\n"
"border-radius: 12px;}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(180, 0, 0);  /* Vermelho mais escuro */\n"
"    border-color: rgb(180, 0, 0);  /* Bordas também mais escuras */\n"
"}\n"
"")
        self.btn_close.setObjectName("btn_close")
        self.btn_close.clicked.connect(MainWindow.close)

        self.frame_2.raise_()
        self.frame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "PBSTOCK"))
        self.label_3.setText(_translate("MainWindow", "OLÁ CARO COLABORADOR, SEJA BEM-VINDO\n"
"CASO AINDA NÃO TENHA UM LOGIN CONTATE \n"
"SEU SUPERVISOR PARA CRIÁ-LO.\n"
""))
        self.label_4.setText(_translate("MainWindow", "Acesso ao Sistema"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Usuário"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Senha"))
        self.pushButton.setText(_translate("MainWindow", "Acessar Sistema"))
        self.btn_close.setText(_translate("MainWindow", "X"))
        
        self.centralwidget.mousePressEvent = self.mousePressEvent
        self.centralwidget.mouseMoveEvent = self.mouseMoveEvent
        
    def mousePressEvent(self, event):
        self.dragPos = event.globalPos()
    
    def mouseMoveEvent(self, event):
        if hasattr(self, 'dragPos'):
            self.MainWindow.move(self.MainWindow.pos() + event.globalPos() - self.dragPos)
            self.dragPos = event.globalPos()
            event.accept()

from view.QRC import file_rc



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_login()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())